### ISSUE TITLE
Problem when trying to use Factories

### ISSUE THREAD

**Issue by samirgit** [lucid-architecture/laravel#1]
i couldn't load database factories located in [ src/Services/{serviceName}/Database/factories ],

the Illuminate\Database\Eloquent\Factory class has a static constructor, i tried to change the factory paths by placing the below inside my `ServiceProvider::register()` function

<pre>
$faker =  new Faker;
$this->app->singleton(Factory::class, function () use ($faker) {
      return Factory::construct($faker, realpath(__DIR__.'/../Database/factories'));
});
</pre>

now the factories are available but for some reason faker stopped working properly, giving `Unknown formatter "xx"`  errors

**Comment by Mulkave** [comment]
What's the folder structure like for the database factories in your service ?

**Comment by samirgit** [comment]
So i have an API service,

Structure for the factories: src/Services/Api/Database/factories/[All files here]

**Comment by Mulkave** [comment]
I assume that your custom factories under that directory are recognised by the service (reached and being read _i.e. if you `dd('something')` inside that file it will die and dump it_), the formatter issue is considered as a Faker issue in that case. See https://github.com/fzaninotto/Faker/issues/344 and https://github.com/fzaninotto/Faker/issues/441

Can you confirm?

**Comment by Mulkave** [comment]
@samirgit any updates on your issue?

**Comment by samirgit** [comment]
@Mulkave last comment Dec 2015, rebooting project in sep 15, gonna start fresh 

joined Speed@BDD, i have seen you listed as a mentor, still there?

**Comment by Mulkave** [comment]
@samirgit yep
