### ISSUE TITLE
Upgrade to laravel 5.4

### ISSUE THREAD

**Issue by dstollie** [lucid-architecture/laravel#16]
After watching the talk on Laracan Amsterdam I was really excited to use lucid for our next application. Unfortunately Lucid is is not yet build to be compatible with laravel 5.4. Could lucid be upgraded to use laravel 5.4?

**Comment by adibhanna** [comment]
@dstollie I asked the same question to @Mulkave and I believe he's going to upgrade it really soon.

**Comment by dstollie** [comment]
@adibhanna thanks, Ill wait with excitement :)

**Comment by adibhanna** [comment]
@dstollie Lucid is upgraded to L5.4 :)
