### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by n00el** [lucid-architecture/laravel#22]
Hello. 
Any future plan abaut update to laravel 5.5?
I really need this! 👍

**Comment by Mulkave** [comment]
Hello @n00el, expected this weekend 😄

**Comment by jerrebm** [comment]
@Mulkave Is this still happening? 😃

**Comment by Mulkave** [comment]
Yes! Unfortunately things got messy on my side 😓 should be by the end of this week. Sorry!

Appreciate a PR if someone can before then.

**Comment by Mulkave** [comment]
Thanks to @harris21 we have it now 😄 https://github.com/lucid-architecture/laravel/tree/master

Extremely sorry for this delay!
