### ISSUE TITLE
Method [dispatchFromArray] does not exist.

### ISSUE THREAD

**Issue by olehhrynkiv** [lucid-architecture/laravel#24]
BadMethodCallException in Controller.php line 107:
Method [dispatchFromArray] does not exist.

I'm checking DispathcesJobs trait and this method doesn't exist. I've installed 5.2.x

**Comment by olehhrynkiv** [comment]
also abstract class Feature has method run which also uses unexisting usesdispatchForm and dispatchFromArray methods

**Comment by harris21** [comment]
@olehhrynkiv Can you provide more information on how to replicate this error?

**Comment by olehhrynkiv** [comment]
sorry guys, my bad. Maybe I've used some wrong package, have checked 5.2 branch and it does work well. Still can't get how did I face this issue. In my installation Feature class is in App\Foundation and uses dispatchFrom and dispatchFromArray
