### ISSUE TITLE
How to access to the statistics views

### ISSUE THREAD

**Issue by skalero01** [lucid-architecture/laravel#27]
Hi, i just saw the conference about the lucid architecture on youtube (https://www.youtube.com/watch?v=wSnM4JkyxPw)

In the minute 31:20 a dashboard with statistics about the code is shown but in the readme file and on the wiki there is not any information about how to get it working.

Does anyone know how to anable this feature?

**Comment by harris21** [comment]
Hey @skalero01 , is https://github.com/lucid-architecture/laravel#launching-the-interactive-console-ui what you are looking for?
