### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by jeffegiovani** [lucid-architecture/laravel#29]
Hi Dears!
The upgrade to Laravel 5.6 is on the roadmap?

Regards!

**Comment by harris21** [comment]
Hey @jeffegiovani , yes definitely! We'll try to find some time and add the v5.6 upgrade. Meanwhile, any PRs on this matter are welcome!

**Comment by n00el** [comment]
Any info about 5.6? When will you release it?

**Comment by harris21** [comment]
Updated to Laravel v5.6 in https://github.com/lucid-architecture/laravel/pull/30. Cheers!
