### ISSUE TITLE
It does not seem to work

### ISSUE THREAD

**Issue by bart** [lucid-architecture/laravel#3]
Unfortunately it doesn't seem to work correctly. When following the instructions from the README I'm getting "BadMethodCallException in Controller.php line 79: Method [dispatchFromArray] does not exist."

I wanted to start a new project because everything has sound so good at your Laracon EU talk. But it seems like lucid isn't production ready yet, isn't it?

**Comment by adammcd9** [comment]
Before I open a separate issue, does your project have Laravel 5.2, or 5.3? I'm following the download instructions but by default it is downloading 5.2, not 5.3 as stated in the docs.

**Comment by bart** [comment]
I did try out both versions. I already created another issue for the 5.3 problem but it hasn't to do anything with this issue here. You can get 5.3 by using lucid-arch/laravel=dev-master

**Comment by Mulkave** [comment]
@bart Can you please confirm that you have registered the service after creating it? https://github.com/lucid-architecture/laravel#register-service

**Comment by Mulkave** [comment]
@Nublust It is now 5.3 by default and there are 5.2 and 5.1 versions. Please see #2

**Comment by bart** [comment]
@Mulkave I think there is a difference between stub, console output and documentation here. The handle() method in ServiceProvider does not exist. We only have a register() method here where I've added it to, yes. Btw. I've created a pull request for the laravel-console package that fixes some wrong stub paths

**Comment by Mulkave** [comment]
@bart oops, that's a type-o over there. Thanks a bunch for this and for the PR in console.
