### ISSUE TITLE
Object of class could not be converted to string

### ISSUE THREAD

**Issue by ModestasBlazys** [lucid-architecture/laravel#31]
Hi,

Found this by accident.

MarshalTrait.php, Line 61

`throw new Exception("Unable to map parameter [{$parameter->name}] to command [{$command}]");`

when I hit this line received following error

Object of class could not be converted to string

I suspect that it complains about $command

Thanks

**Comment by harris21** [comment]
Hey @ModestasBlazys , I could not replicate the issue. Is this still the case? Could you please elaborate on this?
