### ISSUE TITLE
lucid now support lumen? and how integrate with lumen

### ISSUE THREAD

**Issue by MattCraftsCode** [lucid-architecture/laravel#32]
lucid now support lumen? and how integrate with lumen

**Comment by harris21** [comment]
Lucid doesn't support Lumen at the moment.
This is tricky because Lucid uses most of Laravel's supported packages, which is something that Lumen doesn’t include by default.

**Comment by dothem1337** [comment]
Is the speed still enought for microservices? Lumen is build for microservices, Laravel not.

**Comment by Mulkave** [comment]
@dothem1337 depends on your expectation of speed. In our experience it has always been more than enough, a system made up of around 14 services based on [Laravel-microservice](https://github.com/lucid-architecture/laravel-microservice) package which has a slightly different structure.

In most cases, you'll be fine using either of these options. The constraints of Lucid-Lumen is what Harris mentioned, that we'll end up re-building Laravel within Lument if we were to add the packages.
