### ISSUE TITLE
Lucid Dashboard not showing

### ISSUE THREAD

**Issue by jbaron-mx** [lucid-architecture/laravel#35]
Hello,

Did a fresh 5.6 installation by following the Getting Started instructions, but can't get the Lucid Dashboard to show by visiting the `/lucid/dashboard` page, it is throwing a 404 page instead, looks like the routes are not being registered.

- Working on Homestead 6.4
- Clean installation, no services/features were added.

Any idea on where to look first?

**Comment by harris21** [comment]
Hello @jbaron-mx, I wasn't able to replicate this issue.

Please make sure that you follow the steps mentioned [here](https://github.com/lucid-architecture/laravel#launching-the-interactive-console-ui)
1. Run `php artisan vendor:publish --provider="Lucid\Console\LucidServiceProvider"`
2. Run `php artisan serve` and then visit ` /lucid/dashboard` url as intended

**Comment by jbaron-mx** [comment]
@harris21 You were right. I just re-do all the steps and it's working, my bad. Thank you anyway for checking.
