### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by believe2013** [lucid-architecture/laravel#39]
Is working with multiple versions of api supported?
/api/v1/users
/api/v2/users

**Comment by meletisf** [comment]
No. But you can create a new Api Service and prefix the routes with your api version.

**Comment by Mulkave** [comment]
@believe2013 it is totally up to you to implement the routes within a service. Lucid will only provide a working skeleton but the internals and the decision on these are totally yours!

Please recommend your approach based on your solution when you have it, i am curious to know too.
