### ISSUE TITLE
How to introduce Lucid architecture into an existing project?

### ISSUE THREAD

**Issue by flavioafa** [lucid-architecture/laravel#40]
Hello guys!

I'm starting with Lucid and would like some tips on how to add it to an existing project. How do I add the Lucid library to an existing project? How do I add the Lucid console to an existing project? I would like at the moment to use Lucid just for new features and gradually go refactoring the code to adhere to the architecture. Remembering that the project is monolithic and the idea is that Lucid facilitate a possible change to architecture microservice.

Thank you.

**Comment by harris21** [comment]
Hello @flavioafa, welcome!

There is an article written specifically for people who want to convert their existing Laravel project to [Lucid](https://tech.vinelab.com/convert-laravel-app-architecture-to-lucid-a260541c411b). I suggest you convert your project to https://github.com/lucid-architecture/laravel first, even though it will still be a monolith. This will make your future transition from a monolith to [microservices](https://github.com/lucid-architecture/laravel-microservice) even easier and straight-forward.

I hope this helps, cheers!

**Comment by andreladocruz** [comment]
@harris21 , I tried to install the laravel-console package and it´s not compatible with laravel 6.8.0.

Any idea when it will be compatible?

**Comment by harris21** [comment]
Hello @andreladocruz , could you please some more information? What are the steps to reproduce the issue? (commands etc.)

**Comment by andreladocruz** [comment]
just did a `composer require lucid-arch/laravel-foundation` and then a `composer require lucid-arch/laravel-console`. 

The laravel-console one did not installed because it's dependencies.

**Comment by harris21** [comment]
Hey @andreladocruz, I just tried installing `lucid-arch/laravel-foundation` and `lucid-arch/laravel-console` in a clean Laravel 6.9.0 installation and it worked as expected. 
Please check your application dependencies, seems like a package you are using conflicts with Lucid's requirements.

**Comment by andreladocruz** [comment]
`composer require lucid-arch/laravel-foundation lucid-arch/laravel-console`

 - lucid-arch/laravel-console v6.0.0 requires stevebauman/log-reader ^1.1 -> satisfiable by stevebauman/log-reader[1.1.0].
    - Installation request for lucid-arch/laravel-console ^6.0 -> satisfiable by lucid-arch/laravel-console[v6.0.0].
    - Conclusion: remove laravel/framework v6.9.0
    - Conclusion: don't install laravel/framework v6.9.0
    - stevebauman/log-reader 1.1.0 requires illuminate/support 5.*

 - Installation request for laravel/framework (locked at v6.9.0, required as 6.*) -> satisfiable by laravel/framework[v6.9.0].

**Comment by andreladocruz** [comment]
the 6.0 branch has no stevebauman/log-reader dependency.

the master one has. Maybe that is the problem.

**Comment by andreladocruz** [comment]
if you the release commit (https://github.com/lucid-architecture/console-laravel/commit/5ec3749b8204243e86e59bae82d6e89b90b3201c) you will find that the stevebauman/log-reader dependency was not removed

=P

**Comment by harris21** [comment]
> if you the release commit ([lucid-architecture/console-laravel@5ec3749](https://github.com/lucid-architecture/console-laravel/commit/5ec3749b8204243e86e59bae82d6e89b90b3201c)) you will find that the stevebauman/log-reader dependency was not removed
> 
> =P

@andreladocruz Correct, it was only part of the 6.0 branch and not released. Should be fine now, please check again.

**Comment by andreladocruz** [comment]
Worked... =) 

Thanks... 

Why the lucid commands are not part of artisan list? 

Maybe its a very good feature =) 

We will try thanks.

**Comment by andreladocruz** [comment]
@harris21 , just to let you know that we had to install laravel/helpers package to work properly.
