### ISSUE TITLE
Add Laravel v5.8 support

### ISSUE THREAD

**Issue by harris21** [lucid-architecture/laravel#41]

**Comment by kennyhorna** [comment]
Hello @harris21  do you have an estimated date for the 5.8 compatibility? Thanks in advance.

**Comment by harris21** [comment]
Hey @kennyhorna , no ETA at the moment. I will try to add Laravel v5.8 support as soon as I get the chance though, hopefully by the EOW. Meanwhile, PRs are more than welcome 😄

**Comment by yeftaw** [comment]
Wait for a moment till bugs in laravel 5.8 has been fixed.

**Comment by sasokovacic** [comment]
What's the status? I would like to use Laravel 5.8 because of Laravel Tenancy package...

**Comment by jvv8** [comment]
I can't speak highly enough about Lucid.  
If you have a large project, it's the only way to go in my opinion.
Like many on the 5.8 issue, a 3rd party update has dependancies required for functionality.
Abed, are there problems with the structure integrating with L5.8?
Highest respect,
John VV

**Comment by kennyhorna** [comment]
Hello @harris21  /@Mulkave did you find time to update this amazing project?

**Comment by harris21** [comment]
Hello all, I'll do my best to add Laravel v5.8 support this weekend. Cheers!
