### ISSUE TITLE
Is this project active??

### ISSUE THREAD

**Issue by jakjr** [lucid-architecture/laravel#51]
Hello!

I really enjoy this project, and woud like to know is it still active??

Any other documentation apat from github and the video from laracon?

Thanks.

**Comment by harris21** [comment]
Hi @jakjr ,

you can also take a look at the following posts:
- https://tech.vinelab.com/the-lucid-architecture-serving-features-from-laravels-console-commands-429f81c3aa22
- https://tech.vinelab.com/introducing-operations-the-lucid-architecture-bad45f259a1d
- https://tech.vinelab.com/convert-laravel-app-architecture-to-lucid-a260541c411b

**Comment by meletisf** [comment]
Yes it is active :)
