### ISSUE TITLE
Support for Laravel 6.0?

### ISSUE THREAD

**Issue by ghost** [lucid-architecture/laravel#53]

**Comment by vasymus** [comment]
+1

**Comment by farschmessivo** [comment]
+1

**Comment by fahmifitu** [comment]
Please make it happen

**Comment by laphoung1** [comment]
Please put some efforts to make it for Laravel 6 as this package becomes an important depencies.  And can it be futureproof against any Laravel update ?  Thanks in the name of Laravel community.

**Comment by ghost** [comment]
For everyone wanting an update on this. They made 6.0 branches on some of the core lucid repos a few weeks ago. Nothing has been committed to them last time I checked though.

**Comment by ghost** [comment]
If anyone could make PRs and contribute to the update, that'll probably speed things up

**Comment by fahmifitu** [comment]
I'm honestly clueless about this if I knew I would totally help.

**Comment by soutorafaelbr** [comment]
+1

**Comment by vov4ik08** [comment]
Hello. Does it make sense to wait for the upgrade to the version 6 ?

**Comment by ghost** [comment]
> Hello. Does it make sense to wait for the upgrade to the version 6 ?

No it doesn't make sense. This should've been done long time ago.

**Comment by vov4ik08** [comment]
> No it doesn't make sense. This should've been done long time ago.
|  
-- | --

Too bad!

**Comment by harris21** [comment]
Sorry for the delay people, enjoy!
