### ISSUE TITLE
laravel/helpers dependency missing

### ISSUE THREAD

**Issue by RicardoRodriguesGuru** [lucid-architecture/laravel#60]
I recently started a migration of a laravel project to lucid, so I ran the `composer require lucid-arch/laravel-foundation lucid-arch/laravel-console` command.

When I tried to generate a service with the `lucid make:service web` command, it gave a `PHP Fatal error: Uncaught Error: Call to undefined function Lucid\Console\studly_case()` error.

I fixed it by adding the dependency laravel/helpers to my project. I think you can use the `Str` Laravel helpers to do that instead of that dependency. If you can't modify the code, maybe you can add the dependency to your packages so the migrations can be done more smoothly.

**Comment by kohlerdominik** [comment]
This was fixed in [804e562](https://github.com/lucid-architecture/console-laravel/commit/804e5629d3169039e1fe3482cbc526a731cf5c85).

@Mulkave I suggest to close this because it's fixed in the 7.x.
