### ISSUE TITLE
The requested package lucid-arch/laravel-foundation ^7.0 exists as lucid-arch/laravel-foundation ...

### ISSUE THREAD

**Issue by vov4ik08** [lucid-architecture/laravel#64]
Hello. Try to install new project, use commad
composer create-project lucid-arch/laravel my-project
and get error

Problem 1
    - The requested package lucid-arch/laravel-foundation ^7.0 exists as lucid-arch/laravel-foundation[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.2, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.0.x-dev, dev-master, v5.1.0, v5.1.1, v5.2.0, v5.2.1, v5.3.0, v5.3.1, v5.3.2, v5.3.3, v5.3.4, v5.4.0, v5.4.1, v5.4.3, v5.4.4, v5.5.0, v5.5.1, v5.5.2, v5.5.3, v5.5.4, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.7.0, v5.7.1, v5.8.0, v5.8.1, v6.0.0] but these are rejected by your constraint.

I use php 7.4.5, please help

**Comment by Mulkave** [comment]
Ouch, sorry about that. Version wasn't released yet. It is now! Please go ahead and try re-creating the project.

**Note:** You may need to create the project again because composer might try to load from cache and give the same error.
