### ISSUE TITLE
Turn off lucid routes

### ISSUE THREAD

**Issue by nicopenaredondo** [lucid-architecture/laravel#70]
Any idea on how to turn off the routes of lucid ? 

![image](https://user-images.githubusercontent.com/3615451/94567523-255ef300-029e-11eb-82d7-1df38c75161c.png)

**Comment by Mulkave** [comment]
Please publish Lucid's config:

```
php artisan vendor:publish --provider="Lucid\Console\LucidServiceProvider"
```

Then open `config/lucid.php`, initially `dashboard=null` set it to `false` and they will no longer show up in `route:list`

**Note:** careful this will also publish some files in `public/vendor/lucid` that you might want to remove if you won’t use the dashboard.

**Comment by nicopenaredondo** [comment]
got it thanks @Mulkave
