### ISSUE TITLE
Support for Laravel 8.x?

### ISSUE THREAD

**Issue by vov4ik08** [lucid-architecture/laravel#71]
Hello. Have you a plan to deploy your, cool, librarary for laravel 8.x

**Comment by undjike** [comment]
Really need it on Laravel 8. I'm delaying a new project for this...

**Comment by undjike** [comment]
I created an issue on naming convention [issue](https://github.com/lucid-architecture/laravel-microservice/issues/19) on **lucid-architecture/laravel-microservices**. Just for you not to forget it on migrating this project to Laravel 8.

Also, depending on your considerations about the scope of this project, are you planning to consider Livewire implementation on services ?

Finally, I would like if you could state how to run a service's migration.

**Comment by Mulkave** [comment]
@vov4ik08 @undjike sorry for the delay on this. It is available now! 

N.B. There's a change coming next month to the way you install Lucid into a project which will get us rid of waiting for an upgrade of this boilerplate. It will be as simple as `composer require lucid-arch/cli` then `lucid init` which can be run into an existing project as well!

@undjike 
> I created an issue on naming convention [issue](https://github.com/lucid-architecture/laravel-microservice/issues/19) on **lucid-architecture/laravel-microservices**. Just for you not to forget it on migrating this project to Laravel 8.

Thanks! Will fix in Microservice project, here it should be the correct one now.

> Also, depending on your considerations about the scope of this project, are you planning to consider Livewire implementation on services ?

It will be part of the docs for sure, it's been scheduled for the beginning of Dec. If needed earlier please open an issue with details on how you're approaching it and whether you're facing any problems to discuss separately.

> Finally, I would like if you could state how to run a service's migration.

You may use Laravel's `php artisan migrate --path=src/Services/MyService/database/migrations/{file}.php` to specify a custom path for the migration. We intend to keep it familiar by using built-in Laravel commands as much as possible 😄

**Comment by Mulkave** [comment]
I just found [this issue](https://github.com/lucid-architecture/laravel-microservice/issues/18) that you already opened. Thanks for that! Could you please provide more details on what exactly you would like to know? @undjike

**Comment by undjike** [comment]
Waouh so fast. Thanks @Mulkave 
But seems like you made a little mistake on the push. The project's documentation (on **readme.md**) is now the Laravel base readme.

**Comment by Mulkave** [comment]
@undjike oops! Fixed. Thanks!
