### ISSUE TITLE
What to test exactly in a FeatureTest

### ISSUE THREAD

**Issue by websmurf** [lucid-architecture/laravel#8]
Hi there, 

Just wondering about the following. What exact do you advise to test while testing a feature? 
The response of the feature? Or if all steps that are defined are being called? 

Best regards

Adam

**Comment by Mulkave** [comment]
Hi Adam,

Feature tests should be your functional tests, which is where you test it as a "client" with a Request/Response and you would assert the received response to be what you expect the client to receive, similar to [Testing JSON APIs](https://laravel.com/docs/5.3/application-testing#testing-json-apis) of the Laravel docs. Which means you'd make sure that the Feature is exposed correctly through the corresponding Route and Controller, and that it works as expected.

**Comment by websmurf** [comment]
Thanks, that makes sense
